[project]
name = "sft-hybrid"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "deepspeed>=0.18.2",
    "huggingface-hub>=0.36.0",
    "kernels>=0.11.0",
    "trl>=0.25.0",
    "wandb>=0.22.3",
]
